---
name: Algorithm-Line-Bresenham
version: 0.11
author: []
abstract: simple pixellated line-drawing algorithm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.6.1
provides:
  Algorithm::Line::Bresenham:
    file: lib/Algorithm/Line/Bresenham.pm
    version: 0.11
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
